name: build and test

on: [push]

jobs:
  build-Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0

    - name: install Eigen
      run: |
          sudo apt-get update
          sudo apt-get install -y libeigen3-dev
    - name: build and run
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ./nanospline_test

  build-MacOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1

    - name: install Eigen
      run: |
          brew update
          brew install eigen
    - name: build and run
      run: |
        git submodule update --init
        mkdir build
        cd build
        cmake ..
        make
        ./nanospline_test

  build-Windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1

    - name: build and run
      run: |
        git submodule update --init
        git clone https://github.com/PyMesh/eigen.git
        mkdir build
        cd build
        cmake .. -DEigen3_DIR=$Env:GITHUB_WORKSPACE\nanospline\eigen -DCMAKE_GENERATOR_PLATFORM=x64
        cmake --build . --config Release
